#!/usr/bin/env bash

# install -- make symbolic links in the users home directory
# Mike Barker <mike@thebarkers.com>
# May 14th, 2013

# 2015.04.30 MRB
# Renamed from makelinks.sh to install.sh
# Force create the sympolic links

# 2016.04.21 MRB
# - Rewrite to be less generic

# Create a symbolic link, backing up any files that exist
link() {
	local src=$1
	local dst=$2
	echo "Linking ${dst} to ${src} ..."
	if [ -a ${dst} ]; then
		if ! [ -h ${dst} ]; then
			echo "Backing up ${dst} to ${dst}.backup"
			mv ${dst} ${dst}.backup
		fi
	fi
	ln -fsvn ${src} ${dst}
}

# Get the current working directory
CWD="$(cd "$(dirname "$0")" && pwd)"

# Link the vim configuration files and dir
echo "Make sympolic links in the users home directory to the vim config files and directories"
link ${CWD}/vimrc ${HOME}/.vimrc
link ${CWD}/vim ${HOME}/.vim

# Clone the Vundle plugin manager
echo "Git clone the Vundle plugin manager..."
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# Install the plugins
echo "Install the defined plugins..."
vim +PluginInstall +qall
